# Generated by Django 2.0.1 on 2018-03-13 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_auto_20180313_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayhome',
            name='infomation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Informations'),
        ),
    ]
