# Generated by Django 2.0.1 on 2018-03-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_displayhome_infomation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='displayhome',
            old_name='infomation',
            new_name='information',
        ),
    ]
