# Generated by Django 2.0.1 on 2018-03-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_auto_20180313_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
